# Generated by Django 5.1.4 on 2026-03-22 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_material', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('reviews_stars', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('colours', models.JSONField(blank=True, default=list)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_long_description', models.TextField(blank=True, null=True)),
                ('product_other_specifications', models.TextField(blank=True, null=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('second_image_1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('in_stock', models.BooleanField(default=True)),
                ('deals', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='USER', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Refunded', 'Refunded')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.loginmodule')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.loginmodule')),
            ],
        ),
        migrations.CreateModel(
            name='PetModule',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('pet_photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('pet_qr_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_lost', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='appmodule.loginmodule')),
            ],
        ),
        migrations.CreateModel(
            name='PetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='appmodule.petmodule')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=200)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appmodule.loginmodule')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appmodule.petmodule')),
            ],
        ),
        migrations.CreateModel(
            name='PetRemainders',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('Health', 'Health'), ('Grooming', 'Grooming'), ('Activity', 'Activity'), ('Nutrition', 'Nutrition'), ('Administrative', 'Administrative')], max_length=50)),
                ('alert_subtype', models.CharField(choices=[('Vaccination', 'Vaccination'), ('Medication', 'Medication'), ('Vet Appointment', 'Vet Appointment'), ('Deworming', 'Deworming'), ('Flea Treatment', 'Flea Treatment'), ('Bath', 'Bath'), ('Nail Trimming', 'Nail Trimming'), ('Teeth Cleaning', 'Teeth Cleaning'), ('Walk', 'Walk'), ('Exercise', 'Exercise'), ('Insurance Renewal', 'Insurance Renewal'), ('License Renewal', 'License Renewal')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('remainder_date', models.DateField()),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('One-time', 'One-time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.petmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.loginmodule')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appmodule.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.loginmodule')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.petmodule')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=120)),
                ('owner_address', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_city', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_state', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_photo', models.ImageField(blank=True, null=True, upload_to='owner_photos/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='appmodule.loginmodule')),
            ],
        ),
    ]
