# Generated by Django 5.2.5 on 2025-09-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
    ]
