# Generated by Django 5.1.4 on 2026-04-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0002_order_cancelled_at_order_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodule',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
