# Generated by Django 5.2.5 on 2025-09-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0002_remove_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owner_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
