# Generated by Django 5.2.5 on 2025-09-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0003_userprofile_owner_city_userprofile_owner_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('product_info', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('reviews', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
