# Generated by Django 5.1.4 on 2026-04-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0003_petmodule_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodule',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
