# Generated by Django 5.1.4 on 2026-04-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0004_petmodule_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petalert',
            name='is_resolved',
            field=models.TextField(default=False),
        ),
    ]
