# Generated by Django 5.2.5 on 2025-10-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0005_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('In Cart', 'In Cart'), ('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='In Cart', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.loginmodule')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.petmodule')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.product')),
            ],
        ),
    ]
