# Generated by Django 5.2.5 on 2025-11-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
