# Generated by Django 5.1.4 on 2026-07-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0006_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_type',
            field=models.CharField(default='Other Pet Document', max_length=50),
        ),
    ]
