# Generated by Django 5.1.4 on 2025-12-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0007_product_deals'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAlerts',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('Vaccination', 'Vaccination'), ('Medication', 'Medication'), ('Appointment', 'Appointment')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('frequency', models.CharField(choices=[('One-time', 'One-time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.petmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.loginmodule')),
            ],
        ),
    ]
