# Generated by Django 5.1.4 on 2025-12-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0008_petalerts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petalerts',
            old_name='cart_id',
            new_name='alert_id',
        ),
    ]
